// Re-exports for backward compatibility. Actual data lives in src/constants/questionnaires/
export type { QuestionnaireOption, QuestionnaireQuestion, Questionnaire } from './questionnaires/types'
export { AC_Q } from './questionnaires/acq'
export { CAT } from './questionnaires/cat'
export { AUDIT_C } from './questionnaires/auditc'
export { FAGERSTROM_NICOTINE_DEPENDENCE } from './questionnaires/fagerstrom'
export { FINDRISC } from './questionnaires/findrisc'
export { MORISKY } from './questionnaires/morisky'
export { B_IPQ } from './questionnaires/bipq'
export { PSS } from './questionnaires/pss'
